spring:
  application:
    name: Hospital System
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: Ahmad
  jpa:
    hibernate:
      default_schema: hospital
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: hospital
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    user: postgres
    password: Ahmad

