spring:
  application:
    name: Hospital System
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: Ahmad
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: hospital
    baseline-on-migrate: true
    baseline-version: 0
    user: postgres
    password: Ahmad
  jackson:
    mapper:
      ALLOW_COERCION_OF_SCALARS: false
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    gcp:
      storage:
        projectId: focused-evening-348416
      credentials:
        location: classpath:/focused-evening-348416-8edd3cea197f.json




